name: Sincronizar com Hugging Face
on:
  push:
    branches: [ main ]
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Sincronizar com o HF
        uses: huggingface/hub-sync@v0.1.0
        with:
          github_repo_id: ${{ github.repository }}
          hf_repo_id: weslleyls/reembolso
          hf_token: ${{ secrets.HF_TOKEN }}
